### ISSUE TITLE
Allow making new releases when a new binary version is available

### ISSUE THREAD

**Issue by jeronimoalbi** [ignite/ignite-files#23]
We should be able to make new releases when a new Hermes or Gex binary is available.

**Comment by Pantani** [comment]
We should save the latest version of the binary we are currently using so we can check if there is a new version. Now, we are tagging the repo with the binary version. For instance, if we use the `v1.8.1` hermes binary, the `ignite-files` repo tag name will be `hermes/v1.8.1`. This could help, and it would be awesome if the new binary could automatically create the new tag.
